Telefon_Rehberi/Telefon_Rehberi/Controllers/AdminUIController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telefon_Rehberi;
using Telefon_Rehberi.ViewModel;

namespace Telefon_Rehberi.Controllers
{
    public class AdminUIController : Controller
    {

        public ActionResult Login()
        {
            Admin adminlogin = new Admin();


            return View(adminlogin);
        }
        [HttpPost]
        public ActionResult Login(Admin admin)
        {


            using (TelefonRehberiEntities db = new TelefonRehberiEntities())
            {


                var usr = db.Admin.SingleOrDefault(a => a.AdminEposta == admin.AdminEposta && a.AdminSifre == admin.AdminSifre);
                if (usr != null)
                {
                    Session["userID"] = usr.AdminID.ToString();
                    Session["userEposta"] = usr.AdminEposta.ToString();
                    return RedirectToAction("adminAnaSayfa");
                }
                else
                {
                    ModelState.AddModelError("", "eposta veya şifre yanlış");
                }

            }

            return View();

        }

        public ActionResult adminAnaSayfa()
        {


            if (Session["userID"] != null)
            {
                TelefonRehberiEntities db = new TelefonRehberiEntities();
                var calisan = new List<Calisanlar>();
                calisan = db.Calisanlar.ToList();

                return View(calisan);

            }
            else
            {
                return RedirectToAction("Login");
            }


        }
        public ActionResult AdminHomePage()
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();
            var calisan = new List<Calisanlar>();
            calisan = db.Calisanlar.ToList();

            return View(calisan);

        }

        public ActionResult CalisanEkle()
        {
            List<Calisanlar> calisan = new List<Calisanlar>();
            List<Departmanlar> departman = new List<Departmanlar>();
            List<YöneticiBilgileri> yonetici = new List<YöneticiBilgileri>();
            using (TelefonRehberiEntities db = new TelefonRehberiEntities())
            {
                departman = db.Departmanlar.OrderBy(a => a.DepartmanAdi).ToList();
                calisan = db.Calisanlar.ToList();
                yonetici = db.YöneticiBilgileri.OrderBy(a => a.YöneticiAdi).ToList();

            }
            ViewBag.DepartmanId = new SelectList(departman, "DepartmanID", "DepartmanAdi");
            ViewBag.YoneticiId = new SelectList(yonetici, "YöneticiID", "YöneticiAdi");

            return View();
        }
        [HttpPost]
        public ActionResult CalisanEkle(Calisanlar calisan)
        {
            if (ModelState.IsValid)
            {


                using (TelefonRehberiEntities db = new TelefonRehberiEntities())
                {
                    db.Calisanlar.Add(calisan);
                    db.SaveChanges();
                }

                return RedirectToAction("AdminHomePage");
            }

            return View();


        }
        public ActionResult Duzenle(int id=0)
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();
            List<Departmanlar> departman = new List<Departmanlar>();
            List<YöneticiBilgileri> yonetici = new List<YöneticiBilgileri>();

            departman = db.Departmanlar.OrderBy(a => a.DepartmanAdi).ToList();
            yonetici = db.YöneticiBilgileri.OrderBy(a => a.YöneticiAdi).ToList();

            ViewBag.DepartmanId = new SelectList(departman, "DepartmanID", "DepartmanAdi");
            ViewBag.YoneticiId = new SelectList(yonetici, "YöneticiID", "YöneticiAdi");

            Calisanlar calisan = db.Calisanlar.Single(a => a.CalisanId == id);
            return View(calisan);
        }
        [HttpPost]
        public ActionResult Duzenle(Calisanlar c )
        {

            using (TelefonRehberiEntities db = new TelefonRehberiEntities())
            {
                var v = db.Calisanlar.Where(a => a.CalisanId.Equals(c.CalisanId)).FirstOrDefault();

                if (v!=null)
                {
                    v.Adi = c.Adi;
                    v.Soyadi = c.Soyadi;
                    v.Telefon = c.Telefon;
                    v.DepartmanID = c.DepartmanID;
                    v.YöneticiID = c.YöneticiID;
                }
                db.SaveChanges();
                return RedirectToAction("AdminHomePage");
            }

                
                //Calisanlar calisan = db.Calisanlar.SingleOrDefault(a=>a.CalisanId==c.CalisanId);
                //db.Entry(c).State = System.Data.Entity.EntityState.Modified;
                //db.SaveChanges();
                //return RedirectToAction("AdminHomePage");
            
            
            
        }
        public ActionResult sil(int id = 0)
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();
            Calisanlar calisan = db.Calisanlar.SingleOrDefault(a => a.CalisanId == id);

            if (calisan == null)
            {
                return HttpNotFound();
            }
            return View(calisan);
        }
        [HttpPost, ActionName("sil")]
        public ActionResult silconfirm(int id)
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();
            Calisanlar calisan = db.Calisanlar.SingleOrDefault(a => a.CalisanId == id);
            db.Calisanlar.Remove(calisan);
            db.SaveChanges();

            return RedirectToAction("adminHomePage");
        }

        public ActionResult SifreDegistir()
        {
            AdminModel admin = new AdminModel();

            return View(admin);
        }
        [HttpPost]
        public ActionResult SifreDegistir(AdminModel model)
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();
            if (model.YeniSifre != model.SifreDogrula)
            {
                return View(model);
            }
            var mail = GetUser(model.Eposta);
            if (mail)
            {
                var reset = db.Admin.SingleOrDefault(a => a.AdminEposta == model.Eposta);
                reset.AdminSifre = model.YeniSifre;
                db.SaveChanges();
                ModelState.AddModelError("", "Şifre Başarılı Bir Şekilde Değiştirlmiştir");
                return View(model);

            }

            ModelState.AddModelError("", "E-posta veya Şifre Yanlış");

            return View(model);
        }
        public bool GetUser(string user)
        {
            using (TelefonRehberiEntities db = new TelefonRehberiEntities())
            {
                if (db.Admin.Any(a => a.AdminEposta == user))
                {
                    return true;
                }
                return false;
            }
        }
        public ActionResult departman()
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();

            return View(db.Departmanlar);
        }
        public ActionResult DepartmanDuzenle(int id)
        {
            using (TelefonRehberiEntities db=new TelefonRehberiEntities())
            {
                var departman = db.Departmanlar.Find(id);
                Departmanlar model = new Departmanlar()
                {
                    DepartmanId = departman.DepartmanId,
                    DepartmanAdi = departman.DepartmanAdi
                };
                return View(model);
            }
        }
        [HttpPost]
        [ActionName("DepartmanDuzenle")]
        public ActionResult DepartmanDuzenlee(int id)
        {
            
            using (TelefonRehberiEntities db = new TelefonRehberiEntities())
            {
                var departman = db.Departmanlar.Single(a => a.DepartmanId == id);
                UpdateModel(departman);
                if (ModelState.IsValid)
                {
                    db.SaveChanges();

                    return RedirectToAction("departman");
                }
                return View(departman);
            }
              
        }

        public ActionResult DepartmanEkle()
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();
            var departman= db.Departmanlar.ToList();

            return View();

        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departmanlar d)
        {


            using (TelefonRehberiEntities db = new TelefonRehberiEntities())
            {
                db.Departmanlar.Add(d);
                db.SaveChanges();
            }

            return RedirectToAction("departman");

        }
        public ActionResult DepartmanSil(int id)
        {
            TelefonRehberiEntities db = new TelefonRehberiEntities();
            Departmanlar departman = db.Departmanlar.Single(a => a.DepartmanId == id);
           

            if (departman.Calisanlar.Count==0)
            {
                db.Departmanlar.Remove(departman);
                db.SaveChanges();
                return RedirectToAction("departman");
            }
            else
            {


                return View();
            }
              

           

        }
       
       
       
    }
}

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/AdminHomePage.cshtml
@model IEnumerable<Telefon_Rehberi.Calisanlar>

@{
    ViewBag.Title = "Admin Sayfası";
}

<br />
<br />

<p>
    @Html.ActionLink("Yeni Çalışan Ekle", "CalisanEkle")
</p>
<p>
    @Html.ActionLink("Şifre Değiştir", "SifreDegistir")
</p>
<p>
    @Html.ActionLink("Departman Düzenle", "departman")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Adi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Soyadi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefon)
        </th>
        <th>
            @Html.DisplayName("Departman")
        </th>
        <th>
            @Html.DisplayName("Yönetici Bilgisi")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Adi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Soyadi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departmanlar.DepartmanAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YöneticiBilgileri.YöneticiAdi)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Duzenle", new {  id=item.CalisanId }) |
           
            @Html.ActionLink("Sil", "sil", new {  id=item.CalisanId })
        </td>
    </tr>
}

</table>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/CalisanEkle.cshtml
@model Telefon_Rehberi.Calisanlar

@{
    ViewBag.Title = "Calisan Ekle";
}

<h2>Calisan Ekle</h2>

@using (Html.BeginForm("CalisanEkle","AdminUI",FormMethod.Post,new { @class="form-horizontal"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      <br />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Departman", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DepartmanID,ViewBag.departmanId as SelectList,"Departman Seçiniz" , new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Yönetici Bilgisi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.YöneticiID, ViewBag.yoneticiId as SelectList, "Yönetici Bilgisi  Seçiniz", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.YöneticiID, "", new { @class = "text-danger" })
            </div>
        </div>
       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ana Sayfaya Geri Dön", "adminAnaSayfa")
</div>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/DepartmanDuzenle.cshtml
@model Telefon_Rehberi.Departmanlar

@{
    ViewBag.Title = "Duzenle";
}

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       <br />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmanAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmanAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmanAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "departman")
</div>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/DepartmanEkle.cshtml
@model Telefon_Rehberi.Departmanlar

@{
    ViewBag.Title = "Departman Ekle";
}

<br />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
   <br />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmanAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmanAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmanAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "departman")
</div>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/DepartmanSil.cshtml
@{
    ViewBag.Title = "DepartmanSil";
}

<h1><span style="color:red">UYARI!</span> Bu departmanda çalışan olduğu için silinemez</h1>
<br />
@Html.ActionLink("Geri Dön", "departman");

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/Duzenle.cshtml
@model Telefon_Rehberi.Calisanlar

@{
    ViewBag.Title = "Duzenle";
}

<h2>Duzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Calisanlar</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Departman", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DepartmanID, ViewBag.departmanId as SelectList, "Departman Seçiniz", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmanID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Yönetici Bilgisi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.YöneticiID, ViewBag.yoneticiId as SelectList, "Yönetici Bilgisi  Seçiniz", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.YöneticiID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/Login.cshtml
@model Telefon_Rehberi.Admin

@{
    ViewBag.Title = "Admin Giriş";
}

<br />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Admin Giriş</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AdminEposta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminEposta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminEposta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdminSifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminSifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminSifre, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Giriş" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/SifreDegistir.cshtml
@model Telefon_Rehberi.ViewModel.AdminModel

@{
    ViewBag.Title = "Sifre Degistir";
}

<h2>Sifre Degistir</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       <br />
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EskiSifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EskiSifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EskiSifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YeniSifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YeniSifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YeniSifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SifreDogrula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SifreDogrula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SifreDogrula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Değiştir" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ana Sayfaya Geri Dön", "adminHomePage")
</div>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/adminAnaSayfa.cshtml
@model IEnumerable<Telefon_Rehberi.Calisanlar>

@{
    ViewBag.Title = "Admin Sayfası";
}

<br />
<br />

<p>
    @Html.ActionLink("Yeni Çalışan Ekle", "CalisanEkle")
</p>
<p>
    @Html.ActionLink("Şifre Değiştir", "SifreDegistir")
</p>
<p>
    @Html.ActionLink("Departman Düzenle", "departman")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Adi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Soyadi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefon)
        </th>
        <th>
            @Html.DisplayName("Departman")
        </th>
        <th>
            @Html.DisplayName("Yönetici Bilgisi")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Adi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Soyadi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departmanlar.DepartmanAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YöneticiBilgileri.YöneticiAdi)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Duzenle", new {  id=item.CalisanId}) |
           
            @Html.ActionLink("Sil", "sil", new {  id=item.CalisanId })
        </td>
    </tr>
}

</table>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/departman.cshtml
@model IEnumerable<Telefon_Rehberi.Departmanlar>

@{
    ViewBag.Title = "departman";
}
<br />
 

<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepartmanAdi)
        </th>
        <th>
            @Html.ActionLink("Ekle", "DepartmanEkle")
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DepartmanAdi)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "DepartmanDuzenle", new { id = item.DepartmanId }) |
            @Html.ActionLink("Sil", "DepartmanSil", new { id = item.DepartmanId })
        </td>
        <td>
          
        </td>
    </tr>

}

</table>

Telefon_Rehberi/Telefon_Rehberi/Views/AdminUI/sil.cshtml
@model Telefon_Rehberi.Calisanlar

@{
    ViewBag.Title = "sil";
}

<h2>sil</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Calisanlar</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Adi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soyadi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyadi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayName("Departman")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departmanlar.DepartmanAdi)
        </dd>
        <dt>
            @Html.DisplayName("Yönetici Bilgisi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YöneticiBilgileri.YöneticiAdi)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>